cracking:
    resource: "@CrackingBundle/Controller/"
    type:     annotation
    prefix:   /

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api

api_cracking:
    resource: "@ApiBundle/Controller/Cracking/"
    type:     annotation
    prefix:   /api/cracking/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
